// Copyright © 2022 Brian Drelling. All rights reserved.

public extension StringInstrument {
    static let bass: Self = .init(
        localizationKey: "bass",
        numberOfStrings: 4,
        numberOfCourses: 1,
        tunings: [
            Tuning.bass.standard,
        ]
    )

    static let guitar: Self = .init(
        localizationKey: "guitar",
        numberOfStrings: 6,
        numberOfCourses: 1,
        tunings: [
            Tuning.guitar.standard,
        ]
    )

    static let irishBouzouki: Self = .init(
        localizationKey: "irish_bouzouki",
        numberOfStrings: 4,
        numberOfCourses: 1,
        tunings: [
            Tuning.irishBouzouki.standard,
        ]
    )

    static let ukulele: Self = .init(
        localizationKey: "ukulele",
        numberOfStrings: 6,
        numberOfCourses: 1,
        tunings: [
            Tuning.ukulele.standard,
        ]
    )
}

// MARK: - Extensions

// TODO: Have this generated by sourcery.
extension StringInstrument: CaseIterable {
    public static var allCases: [Self] = [
        .bass,
        .guitar,
        .irishBouzouki,
        .ukulele,
    ]
}
