// Copyright © 2022 Brian Drelling. All rights reserved.

// TODO: Have this generated by sourcery.
extension StringInstrument: CaseIterable {
    public static var allCases: [Self] = [
        .bass,
        .guitar,
        .irishBouzouki,
        .ukulele,
    ]
}
