// Copyright © 2022 Brian Drelling. All rights reserved.

// TODO: Have this generated by sourcery.
extension StringInstrument: CaseIterable {
    public static var allCases: [Self] = [
        .banjoFiveString,
        .bass,
        .bouzoukiTetrachordo,
        .bouzoukiTrichordo,
        .cello,
        .doubleBass,
        .doubleBassFiveString,
        .fiddle,
        .guitar,
        .irishBouzouki,
        .mandolin,
        .pedalHarp,
        .ukulele,
        .viola,
        .violin,
    ].sorted()
}
