name: Deploy Website

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy_website.yml'
      - 'Plugins/**'
      - 'Snippets/**'
      - 'Sources/**'
      - 'Tests/**'
      - '**.swift'
      - 'Package.resolved'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INSTRUMENTS_FYI_PAT }}
          repository: bdrelling/instruments.fyi
          event-type: InstrumentKit Deployment
