name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test_universal_package_5_3.yml@main
    secrets: inherit
    with:
      scheme: InstrumentKit-Package
